from rest_framework import serializers

class SubmissionSerializer(serializers.Serializer):
    email = serializers.EmailField()
    attachment = serializers.FileField(required=False)
    affiliation = serializers.CharField()
    requester = serializers.CharField(required=False)
    position = serializers.CharField()
    dataType = serializers.CharField(required=False)
    formatOfDataRequested = serializers.CharField(required=False)
    requestingOrganization = serializers.CharField(required=False)
    age = serializers.CharField()
    sex = serializers.CharField(required=False)
    academicBackground = serializers.CharField(required=False)
    profession = serializers.CharField(required=False)
    purpose = serializers.CharField()
    datasetName = serializers.CharField()
    geographicDisaggregation = serializers.CharField(required=False)
    ageDisaggration = serializers.CharField(required=False)
    sexDisaggration = serializers.CharField(required=False)
    otherDisaggregation = serializers.CharField(required=False)
    phone = serializers.CharField()
    consent = serializers.CharField(required=False)
    otherProfession = serializers.CharField(required=False)
